import { defineConfig } from 'tsdown';

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/config.ts',
    'src/middleware/index.ts',
    'src/errors/index.ts',
    'src/registry/index.ts',
    'src/ws/index.ts',
    'src/sse/index.ts',
    'src/commentary/index.ts',
    'src/triggers/index.ts',
    'src/consolidator/index.ts',
    'src/health/index.ts',
    'src/metrics/index.ts',
    'src/replay/index.ts',
  ],
  format: ['esm'],
  platform: 'node',
  target: 'node22',
  outputOptions: {
    entryFileNames: '[name].js',
    chunkFileNames: '[name]-[hash].js',
    preserveModules: true,
    preserveModulesRoot: 'src',
  },
  dts: true,
  clean: true,
  sourcemap: true,
  treeshake: true,
  external: [
    '@graphorin/core',
    '@graphorin/protocol',
    '@graphorin/security',
    '@graphorin/store-sqlite',
    '@graphorin/triggers',
    '@graphorin/agent',
    '@graphorin/memory',
    '@graphorin/sessions',
    '@graphorin/workflow',
    '@hono/node-server',
    '@hono/node-ws',
    'hono',
    'hono/cors',
    'zod',
  ],
});
